name: Linting

on:
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v1
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install requirements
        run: pip install -r requirements/test.txt

      - name: flake8
        run: flake8 --exclude venv --inline-quotes double game

      - name: black
        run: black --line-length 79 --exclude venv --check --skip-string-normalization game
